### ISSUE TITLE
overriding reports on edit

### ISSUE THREAD

**Issue by varCepheid** [Pigmice2733/peregrine-frontend#1496]
When I save a report edit, it shows a pop-up that asks if I want to override the report I had submitted previously. It should override automatically since that's what an edit is for.

**Comment by calebeby** [comment]
This is a bug, and when you tell it to override it (at least sometimes) deletes the report.

**Comment by varCepheid** [comment]
Fix is coming through the backend. This also needs to take care of the issue where edited reports get deleted on save.

**Comment by ev118** [comment]
backend fix
