### ISSUE TITLE
match cards cutting off text

### ISSUE THREAD

**Issue by varCepheid** [Pigmice2733/peregrine-frontend#1536]
![image](https://github.com/Pigmice2733/peregrine-frontend/assets/95455397/d94782f9-40c8-4af3-92e7-3f1729abb60f)
![image](https://github.com/Pigmice2733/peregrine-frontend/assets/95455397/2ab46daa-5f83-4deb-baf7-d16e97e06505)
The match cards don't stretch to accomodate additional text for the playoff matches, which means team numbers get cut off. This issue is not present on event-match and event-team-matches pages, where the match card can widen to fill whatever space it needs. In addition, the cards don't handle 5-character team numbers very well, and the lighter text is too close to the darker text. The first image is the event page; the second image is the event-team-matches page.

**Comment by calebeby** [comment]
@varCepheid I'm not able to reproduce this issue. I went to https://dev.peregrinefrc.com/events/2023orbb (tested in both Chrome and Firefox). Here is how it looks to me:

![image](https://github.com/Pigmice2733/peregrine-frontend/assets/13206945/57a897a1-2204-4477-9624-a2031d271f76)

This screenshot :point_up: is how the design is intended. The "match 1" text (/etc) is supposed to be below the "semis 1" text (/etc). Can you share a link and more testing information (browser, screen width, etc) to help me test this out?

**Comment by varCepheid** [comment]
My pictures were from a branch. I don't remember which one now, probably `manual-matches`. I'll close this and deal with it there.
