### ISSUE TITLE
Cleanup Admin UI

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/peregrine-frontend#541]
The Admin UI is pretty basic since it was just for us, but now that Steel Ridge will be using it we should probably clean it up a bit.

**Comment by calebeby** [comment]
Are you just talking about visually?

**Comment by fharding1** [comment]
Yeah. This is pretty low priority but I still think if another team is gonna be using it it should be cleaned up a little if we have time.

**Comment by calebeby** [comment]
This has been done in #721
