### ISSUE TITLE
Use the latest Preact version

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/peregrine-frontend#563]
git bisect found that 68ab1490039d244258a07e5a9f904ee507af3ccb broke the analysis table sorting. Reverting that commit in f712fbf1fe9d3af2165531bf0738e0fdb07d4dc6 fixed it.

**Comment by fharding1** [comment]
Closed by https://github.com/preactjs/preact/pull/1980/files :smile:

**Comment by calebeby** [comment]
They didn't release the fix yet, we haven't merged https://github.com/Pigmice2733/peregrine-frontend/pull/568 yet

**Comment by fharding1** [comment]
Investigating it is done though ;)

**Comment by calebeby** [comment]
I renamed it :ben:

**Comment by fharding1** [comment]
:penguin_dab:

**Comment by calebeby** [comment]
Closed in #568
