### ISSUE TITLE
Add stat rankings to analysis table

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/peregrine-frontend#573]
This is a feature request we've gotten from people on the team as well as Chad Stryker from Steel Ridge:

The Steel Ridge scouting team really enjoyed using Peregrine at the Oregon Girls Gen event.  The lead scouter told me that this was, by far, the easiest scouting method we have ever used.  Also, since we only had three scouters at the event, being able to share data with your team made it possible for us to develop an effective alliance during the play off rounds.
I would also like to provide some feedback to the Peregrine development team.  While examining the analysis table to evaluate specific teams, I found myself having to repeatedly sort by a column and then manually count rows to determine the rank of the team for the given performance attribute.  It would be very useful if the results table automatically displayed a rank column to make that task easier.  See the attached example.

![Peregrine Rank Column Example](https://user-images.githubusercontent.com/32021905/66324980-51d66e00-e8db-11e9-9d17-1d5e5997d958.jpg)

**Comment by calebeby** [comment]
I renamed it because I wanted to distinguish it from rankings/ranking score/ranking points
