### ISSUE TITLE
Add event search/filtering

### ISSUE THREAD

**Issue by calebeby** [Pigmice2733/peregrine-frontend#574]
From the home page, users should be able to type in a search box to filter the event list. Events whose `key`, `name`, `district`, `fullDistrict`, or `locationName` matches the entered text should be shown.

If you don't want to do the visual styles for the search box, that's ok, I can do it for you.

**Comment by lauramurinova** [comment]
Hello, I would like to try and work on this!

**Comment by calebeby** [comment]
🎉 Awesome! Let me know if you have any questions

**Comment by calebeby** [comment]
@marek-jarab GitHub won't let me assign you to this issue, since you aren't a member of the repo. But I removed the `up-for-grabs` label since you are working on it. Let me know if you need help/have any questions.

Thank you!

**Comment by calebeby** [comment]
@marek-jarab I think if you comment on this issue I can assign you

**Comment by marek-jarab** [comment]
I mean its not necessary but if it is possible to assign me it would be great

**Comment by marek-jarab** [comment]
Thanks

**Comment by calebeby** [comment]
@marek-jarab any luck?

**Comment by marek-jarab** [comment]
Hi. So far I have successfully implemented Filter component to filter mock data, which I have created to test, if search bar work correctly. Now i just need to put it together with your components,so they can cooperate with each other properly.

**Comment by marek-jarab** [comment]
Hi. I have created pull request with name "add event/search filtering". So you can check if you are ok with my implementation.

**Comment by calebeby** [comment]
Closing this because this has been implemented. Thanks @marek-jarab!
